#!/usr/bin/python3
"""MIT License

Copyright (c) 2021 R Sadhukhan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""
import time 
from plyer import notification
print("=========================================")
print("Rend let me Notify :)")
print("Devoloped by :SadhukhanR and SudipC3")
print("=========================================")
a = input('Notification Title:')
m = input('Notification Message:')
t = input('Stay on Message:')
n = eval(input('Notification Repet(in min):'))
q = n*60
if __name__ == "__main__" :
    while True:
        notification.notify(

            title= a ,
            message= m ,
            app_name="Rend",
            ticker= t ,
            toast="true",

            #stay notification 3 sec
            timeout= 3
        )
        # next notification after 10 sec 
        time.sleep(q)

